### ISSUE TITLE
Investigate why Sofia is not using TCP transport explicitly in the Contact header

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/restcomm-ios-sdk#150]
When using TCP as transport. Notice that this is mostly apparent in the INVITE requests due to their size which is pretty big due to WebRTC generated SDP which is huge.

**Comment by atsakiridis** [comment]
That happens because Sofia uses both transports by default (i.e. listens to both tcp and udp port 60). So it uses TCP for Via header since that's what transport was used for the INVITE (because it was too big), but the contact still contains UDP since it can receive packets in UDP as well. So as a behaviour it seems correct. However, if we think that using a single transport will have gains for any reason I could configure it to use only UDP (since it is one mostly used). @gvagenas what do you think?

**Comment by deruelle** [comment]
@atsakiridis can you share some logs so we better see the issue ?
We need to support UDP, TCP and most importantly TLS in the future too as we want all signaling to be secured so we can claim secure calls.

**Comment by atsakiridis** [comment]
@deruelle, here are the logs:

https://gist.github.com/atsakiridis/f77272b627beac276ffe

**Comment by gvagenas** [comment]
@atsakiridis I believe you should use only one transport in order to avoid NAT/Firewall issues. There might be a problem with the NAT pinning if SIP traffic doesn't use the same transport.
Consider also the case where iOS or Android apps will be working over mobile data and you need to reach the client to deliver SIP traffic. In that case it might be necessary to open a NAT port with a SIP OPTIONS and keep it open with SIP OPTIONS also.
Last, there was another use case I was discussing in the past, where Android application using JAIN SIP over TLS to encrypt all SIP traffic, so mobile operators wouldn't block SIP traffic.

**Comment by deruelle** [comment]
Add ;transport=tcp in the contact header so it's clear that all signaling will be on TCP. Given we are using WebRTC, TCP (for testing) and TLS (for production) would be preferred as a default protocol.

**Comment by atsakiridis** [comment]
Ok then, tcp it is, thanks
